spring:
  application:
    name: Hackathon-Test-Task-Backend
  datasource:
    url: jdbc:mysql://w112g2a8y7szlqy6:cjkw30wbdswsdmd9@enqhzd10cxh7hv2e.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/byo2r8yytx7r4chy
    username: w112g2a8y7szlqy6
    password: cjkw30wbdswsdmd9
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    serialization:
      write-dates-as-timestamps: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: vasiliwin17@gmail.com
    password: skukuamzukhugdlp
    properties.mail:
      smtp:
        auth: true
        starttls.enable: true
      protocol: smtps
app:
  cors:
    allowedOrigins: http://localhost:3000,http://localhost:8088